# Generated by Django 5.0.6 on 2024-06-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_create_user_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
