# Generated by Django 5.0.6 on 2024-06-30 09:56

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_remove_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=mysite.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='mysite.user'),
        ),
    ]
